import comp from "D:/Shenb/vuepress-theme-hope/blogs/src/.vuepress/.temp/pages/clips/OpenWrt-Install.html.vue"
const data = JSON.parse("{\"path\":\"/clips/OpenWrt-Install.html\",\"title\":\"OpenWrt 安装教程\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"OpenWrt 安装教程\",\"icon\":\"router\",\"order\":2,\"category\":[\"安装教程\"],\"tag\":[\"OpenWrt\"],\"description\":\"一、准备u盘 准备u盘（后续会被完全擦除），打开wePE（一种常用的WinPE ^1安装工具，其中还包括了许多常用工具）微PE官网 点击“安装到U盘” 设置微PE选项 将DiskImage和esir的OpenWrt镜像放到u盘中 将u盘从电脑拔下 二、写入OpenWrt 1. WinPE安装 插入软路由，给软路由接一套键鼠 插电开机，开机过程中狂按Es...\"},\"headers\":[{\"level\":2,\"title\":\"一、准备u盘\",\"slug\":\"一、准备u盘\",\"link\":\"#一、准备u盘\",\"children\":[]},{\"level\":2,\"title\":\"二、写入OpenWrt\",\"slug\":\"二、写入openwrt\",\"link\":\"#二、写入openwrt\",\"children\":[{\"level\":3,\"title\":\"1. WinPE安装\",\"slug\":\"_1-winpe安装\",\"link\":\"#_1-winpe安装\",\"children\":[]},{\"level\":3,\"title\":\"2. 写入镜像\",\"slug\":\"_2-写入镜像\",\"link\":\"#_2-写入镜像\",\"children\":[]}]},{\"level\":2,\"title\":\"三、初始配置OpenWrt\",\"slug\":\"三、初始配置openwrt\",\"link\":\"#三、初始配置openwrt\",\"children\":[{\"level\":3,\"title\":\"1. 设置密码\",\"slug\":\"_1-设置密码\",\"link\":\"#_1-设置密码\",\"children\":[]},{\"level\":3,\"title\":\"2. 配置软路由网络和端口\",\"slug\":\"_2-配置软路由网络和端口\",\"link\":\"#_2-配置软路由网络和端口\",\"children\":[]},{\"level\":3,\"title\":\"3. 进入OpenWrt面板\",\"slug\":\"_3-进入openwrt面板\",\"link\":\"#_3-进入openwrt面板\",\"children\":[]}]},{\"level\":2,\"title\":\"四（一）OpenWrt的主路由设置\",\"slug\":\"四-一-openwrt的主路由设置\",\"link\":\"#四-一-openwrt的主路由设置\",\"children\":[]},{\"level\":2,\"title\":\"四（二）OpenWrt的旁路由设置\",\"slug\":\"四-二-openwrt的旁路由设置\",\"link\":\"#四-二-openwrt的旁路由设置\",\"children\":[{\"level\":3,\"title\":\"1. 旁路由上的设置\",\"slug\":\"_1-旁路由上的设置\",\"link\":\"#_1-旁路由上的设置\",\"children\":[]},{\"level\":3,\"title\":\"2. 所有流量都经过旁路由的设置\",\"slug\":\"_2-所有流量都经过旁路由的设置\",\"link\":\"#_2-所有流量都经过旁路由的设置\",\"children\":[]},{\"level\":3,\"title\":\"3. 个别机器流量经过旁路由的设置\",\"slug\":\"_3-个别机器流量经过旁路由的设置\",\"link\":\"#_3-个别机器流量经过旁路由的设置\",\"children\":[]},{\"level\":3,\"title\":\"4. 后话\",\"slug\":\"_4-后话\",\"link\":\"#_4-后话\",\"children\":[]}]},{\"level\":2,\"title\":\"五、获取IPv6地址\",\"slug\":\"五、获取ipv6地址\",\"link\":\"#五、获取ipv6地址\",\"children\":[{\"level\":3,\"title\":\"1. 软路由获取IPv6地址\",\"slug\":\"_1-软路由获取ipv6地址\",\"link\":\"#_1-软路由获取ipv6地址\",\"children\":[]},{\"level\":3,\"title\":\"2. 下游设备分配IPv6地址和局域网IPv4地址\",\"slug\":\"_2-下游设备分配ipv6地址和局域网ipv4地址\",\"link\":\"#_2-下游设备分配ipv6地址和局域网ipv4地址\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.22,\"words\":1565},\"filePathRelative\":\"clips/OpenWrt-Install.md\",\"excerpt\":\"<h2>一、准备u盘</h2>\\n<p>准备u盘（后续会被完全擦除），打开wePE（一种常用的WinPE <a href=\\\"WinPE:%E6%9E%81%E5%BA%A6%E7%B2%BE%E7%AE%80%E7%9A%84%E3%80%81%E5%8F%AF%E4%BB%A5%E5%9C%A8U%E7%9B%98%E8%BF%90%E8%A1%8C%E7%9A%84Windows%E7%B3%BB%E7%BB%9F\\\">^1</a>安装工具，其中还包括了许多常用工具）<a href=\\\"https://www.wepe.com.cn/download.html\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">微PE官网</a></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
